# yaml-language-server: $schema=https://deltares.github.io/veriflow/v0/config.schema.json
version: v0
general:
  verification_period:
    dimension: time
    start: "2026-05-15T00:00:00Z"
    end: "2026-06-06T00:00:00Z"
  verification_pairs:
    - variable: QR
      id: QR
      obs: observed
      sim: simulated

datasources:
  - import_adapter: fewswebservice
    source: observed
    data_type: observed_historical
    location_ids:
      - "05BJ010"
    parameter_ids:
      - QR.obs
    module_instance_id: ImportWSC
    webservice_version: "2025.02"

  - import_adapter: fewswebservice
    source: simulated
    data_type: simulated_historical
    location_ids:
      - "05BJ010"
    parameter_ids:
      - QR.sim
    module_instance_id: ElbowRavenHistoric
    webservice_version: "2025.02"

scores:
  - score_adapter: continuous_scores
    scores: [kge, mae, rmse, additive_bias]
    reduce_dims: ["time"]

# datasinks:
#   - export_adapter: cf_compliant_netcdf
#     directory: .
#     filename: Historic_Discharge_Elbow.nc
#     institution: OpenFEWS
#     title: Historic discharge verification
#     force_overwrite: true

id_mapping:
  variable:
    QR:
      observed: QR_obs
      simulated: QR_sim
