# yaml-language-server: $schema=file:///C:/Git/DPyVerification/schemas/0.1.0/config.schema.json


# VSCode shortcuts:
#   Use CTRL+SPACE suggestions of elements
#   USe hovering for information/description about elements

fileversion: 0.1.0
datasources:
  - adapter: fewswebservice
    data_type: ensemble_forecast 
    source_id: dcsm_ecmwf_etc
  - adapter: fewswebservice
    data_type: thresholds
    source_id: "threshold_database"
scores:
  - score: rank_histogram
datasinks: 
  - adapter: cf_netcdf

