name: Build and deploy docs

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build docs
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/docs-build.yml
    with:
      upload-pages-artifact: ${{ github.event_name == 'push' }}

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.ref == 'refs/heads/main' # Deploy on push to main or manual dispatch from main
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5

